//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EServicesCms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LkScreen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LkScreen()
        {
            this.LkScreenValidationMessages = new HashSet<LkScreenValidationMessage>();
        }
    
        public string ScreenId { get; set; }
        public Nullable<int> ParentScreenId { get; set; }
        public string ScreenName { get; set; }
        public string ScreenNameAlt { get; set; }
        public string GroupName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string RedirectUrl { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> RowInsertDate { get; set; }
        public Nullable<System.DateTime> RowUpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LkScreenValidationMessage> LkScreenValidationMessages { get; set; }
    }
}
