//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EServicesCms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCategories_Log
    {
        public int LogId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string DescriptionEng { get; set; }
        public string DescriptionAlt { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> RowInsertDate { get; set; }
        public Nullable<System.DateTime> RowUpdateDate { get; set; }
        public string RowInsertedBy { get; set; }
        public string RowUpdatedBy { get; set; }
        public string IpAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> PrintPreview { get; set; }
        public string CategoryCode { get; set; }
        public string PrintMessage { get; set; }
        public string PrintMessageAr { get; set; }
        public Nullable<bool> TabularLayout { get; set; }
        public string ServiceGuid { get; set; }
        public string CategoryGuid { get; set; }
    }
}
