//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EServicesCms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceVideos_Log
    {
        public int LogId { get; set; }
        public int VideoId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public string NameAlt { get; set; }
        public string VideoUrl { get; set; }
        public string VideoAltUrl { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> RowInsertDate { get; set; }
        public Nullable<System.DateTime> RowUpdateDate { get; set; }
        public string RowInsertedBy { get; set; }
        public string RowUpdatedBy { get; set; }
        public string IpAddress { get; set; }
        public string thumbnailPicture { get; set; }
        public string typeOfVideo { get; set; }
        public string ServiceGuid { get; set; }
        public string CategoryGuid { get; set; }
        public string typeOfVideoAlt { get; set; }
        public string Lingo { get; set; }
    }
}
