//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EServicesCms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLookupOption
    {
        public int OptionId { get; set; }
        public int LookupId { get; set; }
        public string Code { get; set; }
        public string DescriptionAlt { get; set; }
        public string DescriptionEng { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<System.DateTime> RowInsertDate { get; set; }
        public Nullable<System.DateTime> RowUpdateDate { get; set; }
        public string LookUpName { get; set; }
    }
}
